/**
 * Piano B
 * API di interrogazione della blockchain di Zeus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sticazzi@zeuslab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 *  * @param idArticolo  * @param descrizione  * @param lottiEsistenti */
data class Articolo(val idArticolo: kotlin.String? = null, val descrizione: kotlin.String? = null, val lottiEsistenti: kotlin.Array<kotlin.String>? = null
) {
}
