/**
 * Piano B
 * API di interrogazione della blockchain di Zeus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sticazzi@zeuslab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models

import io.swagger.server.models.Operazione

/**
 *  * @param idArticolo  * @param idLotto  * @param operazione */
data class Blockchain(val idArticolo: kotlin.String? = null, val idLotto: kotlin.String? = null, val operazione: kotlin.Array<Operazione>? = null
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Blockchain

        if (idArticolo != other.idArticolo) return false
        if (idLotto != other.idLotto) return false
        if (operazione != null) {
            if (other.operazione == null) return false
            if (!operazione.contentEquals(other.operazione)) return false
        } else if (other.operazione != null) return false

        return true
    }

    override fun hashCode(): Int {
        var result = idArticolo?.hashCode() ?: 0
        result = 31 * result + (idLotto?.hashCode() ?: 0)
        result = 31 * result + (operazione?.contentHashCode() ?: 0)
        return result
    }
}
