/**
 * Piano B
 * API di interrogazione della blockchain di Zeus
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sticazzi@zeuslab.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 *  * @param id  * @param idOperazionePrecedente Hash dell'operazione precedente nella blockchain di appartenenaz * @param descrizione Informazioni inserite dall'operatore riguardo all'operazione eseguita * @param operatore Nome dell'operatore che ha eseguito l'operazione * @param natura Natura dell'operazione eseguita (es. \"semina\")*/
data class Operazione(val id: ByteArray,        /* Informazioni inserite dall'operatore riguardo all'operazione eseguita */
                      val descrizione: kotlin.String,        /* Nome dell'operatore che ha eseguito l'operazione */
                      val operatore: kotlin.String,        /* Natura dell'operazione eseguita (es. \"semina\") */
                      val natura: kotlin.String,
                      val idOperazionePrecedente: String? = null/* Hash dell'operazione precedente nella blockchain di appartenenaz */
) {
}
